[application]

# App (Project) Name
name = "routing-fullstack-example"

# Dioxus App Default Platform
# desktop, web
default_platform = "web"

# `build` & `serve` dist path
out_dir = "dist"

# resource (assets) file folder
asset_dir = "assets"

[web.app]

# HTML title tag content
title = "routing-fullstack-example"

[web.watcher]

# When `dx serve`, it redirects all missing routes to the index.
index_on_404 = true

# When watcher trigger, regenerate the `index.html`.
reload_html = true

# Which files or dirs will be watcher monitoring.
watch_path = ["src", "assets"]

# Include `assets` in web platform.
[web.resource]

# CSS style file
style = ["/tailwind.css"]

# Javascript code file
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
